control "V-89565" do
  title "Global settings defined in common- {account,auth,password,session}
must be applied in the pam.d definition files."
  desc  "Pam global requirements are generally defined in the common-account,
common-auth, common- password and common-session files located in the
/etc/pam.d directory. In order for the requirements to be applied the file(s)
containing them must be included directly or indirectly in each program's
definition file in /etc/pam.d"
  impact 0.5
  tag "severity": nil
  tag "gtitle": "SRG-OS-000069-GPOS-00037"
  tag "gid": "V-89565"
  tag "rid": "SV-100215r1_rule"
  tag "stig_id": "VRAU-SL-000345"
  tag "fix_id": "F-96307r1_fix"
  tag "cci": ["CCI-000192"]
  tag "nist": ["IA-5 (1) (a)", "Rev_4"]
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  tag "check": "Verify that common-{account,auth,password,session} settings are
being applied.

Verify that local customization has occurred in the common-
{account,auth,password,session}-pc file(s) by some method other than the use of
the pam-config utility.

The files \"/etc/pam.d/common-{account,auth,password,session} -pc \" are
auto-generated by \"pam-config\". Any manual changes made to them will be lost
if \"pam-config\" is allowed to run.

# ls -l /etc/pam.d/common-{account,auth,password,session}

If the symlinks point to \"/etc/pam.d/common-
{account,auth,password,session}-pc\" and manual updates have been made in these
files, the updates cannot be protected if pam-config is enabled.

# ls -l /usr/sbin/pam-config

If the setting for \"pam-config\" is not \"000\", this is a finding."
  tag "fix": "In the default distribution of SLES 11, \"/etc/pam.d/common-
{account,auth,password,session}\" are symlinks to their respective
\"/etc/pam.d/common- {account,auth,password,session}-pc\" files. These common-
{account,auth,password,session}-pc files are auto-generated by the pam-config
utility.

Edit /usr/sbin/pam-config permissions to prevent its use:

# chmod 000 /usr/sbin/pam-config"
end

